module.export = (function(){
    global.employees = [
            {id: 1, name: 'Bo Harris'},
            {id: 2, name: 'Corey Pauley'},
            {id: 3, name: 'Kristan Boggs'}, 
            {id: 4, name: 'Justin Bowers'},
            {id: 5, name: 'Steven Haun'},
            {id: 6, name: 'Nathan Zumwalt'},
            {id: 7, name: 'Gary Hooker'},
            {id: 8, name: 'Liz Medina'},
            {id: 9, name: 'Rosemary Finley'},
            {id: 10, name: 'Tammy Hooker'},
            {id: 11, name: 'Tim Langford'},
            {id: 12, name: 'Tony Osterhaus'},
            {id: 13, name: 'Ken Koo'},
            {id: 14, name: 'Allison Collister'},
            {id: 15, name: 'Corbett Guest'},
            {id: 16, name: 'Shay Wilburn'},
            {id: 17, name: 'Jesse Wilson'},
            {id: 18, name: 'Naomy Jones'},
            {id: 19, name: 'Casey Miller'},
            {id: 20, name: 'Jennifer Jennings'},
            {id: 21, name: 'Katrina Hubbard'},
            {id: 22, name: 'Marcus Dickerson'},
            {id: 23, name: 'Mckenzie Munger'},
            {id: 24, name: 'Sam Roh'},
            {id: 25, name: 'Bethany Davidson'},
            {id: 26, name: 'Jason Bonner'},
            {id: 27, name: 'Mckenzi Skinner'},
            {id: 28, name: 'Debbie Potaniec'},
            {id: 29, name: 'Katherine Fajen'},
            {id: 30, name: 'Laura Young'},
            {id: 31, name: 'Robin Jackson'},
            {id: 32, name: 'John Macon'},
            {id: 33, name: 'Cindy Spencer'},
            {id: 34, name: 'John Bratteli'},
            {id: 35, name: 'Nathan Vaughn'}
    ];
})();
